/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    LocationsColumn: typeof import('./src/components/LocationsColumn.vue')['default']
    ModuleColumn: typeof import('./src/components/ModuleColumn.vue')['default']
    ModuleModal: typeof import('./src/components/ModuleModal.vue')['default']
    WorkflowModal: typeof import('./src/components/WorkflowModal.vue')['default']
    WorkflowTable: typeof import('./src/components/WorkflowTable.vue')['default']
  }
}
